# Use the official PHP image based on Alpine Linux
FROM php:7.4-apache

# Set the working directory in the container
WORKDIR /var/www/html

# Copy the application files to the container
COPY . /var/www/html

# Install any additional dependencies (if needed)
# Example: RUN docker-php-ext-install pdo_mysql

# Expose port 80 for Apache
EXPOSE 80

# Start Apache when the container starts
CMD ["apache2-foreground"]

